# https://taskfile.dev

version: '3'

tasks:
  build:
    deps:
      - rustlib-build
    cmds:
      - go build -ldflags="-r lib" .
  rustlib-build:
    dir: lib/imagehash
    cmds:
      - cargo build --release
      - cp target/release/libimagehash.so ../
