// Code generated by ent, DO NOT EDIT.

package imagehash

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imagehash type in the database.
	Label = "image_hash"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageHash holds the string denoting the image_hash field in the database.
	FieldImageHash = "image_hash"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// EdgeUploadTask holds the string denoting the upload_task edge name in mutations.
	EdgeUploadTask = "upload_task"
	// Table holds the table name of the imagehash in the database.
	Table = "image_hashes"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "image_hashes"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_image_hash"
	// UploadTaskTable is the table that holds the upload_task relation/edge.
	UploadTaskTable = "image_hashes"
	// UploadTaskInverseTable is the table name for the UploadTask entity.
	// It exists in this package in order to avoid circular dependency with the "uploadtask" package.
	UploadTaskInverseTable = "upload_tasks"
	// UploadTaskColumn is the table column denoting the upload_task relation/edge.
	UploadTaskColumn = "upload_task_image_hash"
)

// Columns holds all SQL columns for imagehash fields.
var Columns = []string{
	FieldID,
	FieldImageHash,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "image_hashes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"post_image_hash",
	"upload_task_image_hash",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ImageHashValidator is a validator for the "image_hash" field. It is called by the builders before save.
	ImageHashValidator func(string) error
)

// OrderOption defines the ordering options for the ImageHash queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageHash orders the results by the image_hash field.
func ByImageHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageHash, opts...).ToFunc()
}

// ByPostField orders the results by post field.
func ByPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByUploadTaskField orders the results by upload_task field.
func ByUploadTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PostTable, PostColumn),
	)
}
func newUploadTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadTaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UploadTaskTable, UploadTaskColumn),
	)
}
