// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/imagehash"
	"channel-helper-go/ent/post"
	"channel-helper-go/ent/predicate"
	"channel-helper-go/ent/uploadtask"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuidv7 "github.com/moroz/uuidv7-go"
)

// ImageHashQuery is the builder for querying ImageHash entities.
type ImageHashQuery struct {
	config
	ctx            *QueryContext
	order          []imagehash.OrderOption
	inters         []Interceptor
	predicates     []predicate.ImageHash
	withPost       *PostQuery
	withUploadTask *UploadTaskQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ImageHashQuery builder.
func (_q *ImageHashQuery) Where(ps ...predicate.ImageHash) *ImageHashQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ImageHashQuery) Limit(limit int) *ImageHashQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ImageHashQuery) Offset(offset int) *ImageHashQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ImageHashQuery) Unique(unique bool) *ImageHashQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ImageHashQuery) Order(o ...imagehash.OrderOption) *ImageHashQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPost chains the current query on the "post" edge.
func (_q *ImageHashQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(imagehash.Table, imagehash.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, imagehash.PostTable, imagehash.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUploadTask chains the current query on the "upload_task" edge.
func (_q *ImageHashQuery) QueryUploadTask() *UploadTaskQuery {
	query := (&UploadTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(imagehash.Table, imagehash.FieldID, selector),
			sqlgraph.To(uploadtask.Table, uploadtask.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, imagehash.UploadTaskTable, imagehash.UploadTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ImageHash entity from the query.
// Returns a *NotFoundError when no ImageHash was found.
func (_q *ImageHashQuery) First(ctx context.Context) (*ImageHash, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{imagehash.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ImageHashQuery) FirstX(ctx context.Context) *ImageHash {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ImageHash ID from the query.
// Returns a *NotFoundError when no ImageHash ID was found.
func (_q *ImageHashQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{imagehash.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ImageHashQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ImageHash entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ImageHash entity is found.
// Returns a *NotFoundError when no ImageHash entities are found.
func (_q *ImageHashQuery) Only(ctx context.Context) (*ImageHash, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{imagehash.Label}
	default:
		return nil, &NotSingularError{imagehash.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ImageHashQuery) OnlyX(ctx context.Context) *ImageHash {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ImageHash ID in the query.
// Returns a *NotSingularError when more than one ImageHash ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ImageHashQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{imagehash.Label}
	default:
		err = &NotSingularError{imagehash.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ImageHashQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImageHashes.
func (_q *ImageHashQuery) All(ctx context.Context) ([]*ImageHash, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ImageHash, *ImageHashQuery]()
	return withInterceptors[[]*ImageHash](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ImageHashQuery) AllX(ctx context.Context) []*ImageHash {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ImageHash IDs.
func (_q *ImageHashQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(imagehash.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ImageHashQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ImageHashQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ImageHashQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ImageHashQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ImageHashQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ImageHashQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ImageHashQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ImageHashQuery) Clone() *ImageHashQuery {
	if _q == nil {
		return nil
	}
	return &ImageHashQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]imagehash.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.ImageHash{}, _q.predicates...),
		withPost:       _q.withPost.Clone(),
		withUploadTask: _q.withUploadTask.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ImageHashQuery) WithPost(opts ...func(*PostQuery)) *ImageHashQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPost = query
	return _q
}

// WithUploadTask tells the query-builder to eager-load the nodes that are connected to
// the "upload_task" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ImageHashQuery) WithUploadTask(opts ...func(*UploadTaskQuery)) *ImageHashQuery {
	query := (&UploadTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUploadTask = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ImageHash string `json:"image_hash,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ImageHash.Query().
//		GroupBy(imagehash.FieldImageHash).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ImageHashQuery) GroupBy(field string, fields ...string) *ImageHashGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ImageHashGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = imagehash.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ImageHash string `json:"image_hash,omitempty"`
//	}
//
//	client.ImageHash.Query().
//		Select(imagehash.FieldImageHash).
//		Scan(ctx, &v)
func (_q *ImageHashQuery) Select(fields ...string) *ImageHashSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ImageHashSelect{ImageHashQuery: _q}
	sbuild.label = imagehash.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ImageHashSelect configured with the given aggregations.
func (_q *ImageHashQuery) Aggregate(fns ...AggregateFunc) *ImageHashSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ImageHashQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !imagehash.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ImageHashQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ImageHash, error) {
	var (
		nodes       = []*ImageHash{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPost != nil,
			_q.withUploadTask != nil,
		}
	)
	if _q.withPost != nil || _q.withUploadTask != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, imagehash.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ImageHash).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ImageHash{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPost; query != nil {
		if err := _q.loadPost(ctx, query, nodes, nil,
			func(n *ImageHash, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUploadTask; query != nil {
		if err := _q.loadUploadTask(ctx, query, nodes, nil,
			func(n *ImageHash, e *UploadTask) { n.Edges.UploadTask = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ImageHashQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*ImageHash, init func(*ImageHash), assign func(*ImageHash, *Post)) error {
	ids := make([]uuidv7.UUID, 0, len(nodes))
	nodeids := make(map[uuidv7.UUID][]*ImageHash)
	for i := range nodes {
		if nodes[i].post_image_hash == nil {
			continue
		}
		fk := *nodes[i].post_image_hash
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_image_hash" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ImageHashQuery) loadUploadTask(ctx context.Context, query *UploadTaskQuery, nodes []*ImageHash, init func(*ImageHash), assign func(*ImageHash, *UploadTask)) error {
	ids := make([]uuidv7.UUID, 0, len(nodes))
	nodeids := make(map[uuidv7.UUID][]*ImageHash)
	for i := range nodes {
		if nodes[i].upload_task_image_hash == nil {
			continue
		}
		fk := *nodes[i].upload_task_image_hash
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(uploadtask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "upload_task_image_hash" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ImageHashQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ImageHashQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(imagehash.Table, imagehash.Columns, sqlgraph.NewFieldSpec(imagehash.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagehash.FieldID)
		for i := range fields {
			if fields[i] != imagehash.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ImageHashQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(imagehash.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = imagehash.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImageHashGroupBy is the group-by builder for ImageHash entities.
type ImageHashGroupBy struct {
	selector
	build *ImageHashQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ImageHashGroupBy) Aggregate(fns ...AggregateFunc) *ImageHashGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ImageHashGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImageHashQuery, *ImageHashGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ImageHashGroupBy) sqlScan(ctx context.Context, root *ImageHashQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ImageHashSelect is the builder for selecting fields of ImageHash entities.
type ImageHashSelect struct {
	*ImageHashQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ImageHashSelect) Aggregate(fns ...AggregateFunc) *ImageHashSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ImageHashSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImageHashQuery, *ImageHashSelect](ctx, _s.ImageHashQuery, _s, _s.inters, v)
}

func (_s *ImageHashSelect) sqlScan(ctx context.Context, root *ImageHashQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
