// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/post"
	"channel-helper-go/ent/postmessageid"
	"channel-helper-go/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuidv7 "github.com/moroz/uuidv7-go"
)

// PostMessageIdUpdate is the builder for updating PostMessageId entities.
type PostMessageIdUpdate struct {
	config
	hooks    []Hook
	mutation *PostMessageIdMutation
}

// Where appends a list predicates to the PostMessageIdUpdate builder.
func (_u *PostMessageIdUpdate) Where(ps ...predicate.PostMessageId) *PostMessageIdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *PostMessageIdUpdate) SetChatID(v int64) *PostMessageIdUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *PostMessageIdUpdate) SetNillableChatID(v *int64) *PostMessageIdUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *PostMessageIdUpdate) AddChatID(v int64) *PostMessageIdUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *PostMessageIdUpdate) SetMessageID(v int32) *PostMessageIdUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *PostMessageIdUpdate) SetNillableMessageID(v *int32) *PostMessageIdUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *PostMessageIdUpdate) AddMessageID(v int32) *PostMessageIdUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (_u *PostMessageIdUpdate) SetPostID(id uuidv7.UUID) *PostMessageIdUpdate {
	_u.mutation.SetPostID(id)
	return _u
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (_u *PostMessageIdUpdate) SetNillablePostID(id *uuidv7.UUID) *PostMessageIdUpdate {
	if id != nil {
		_u = _u.SetPostID(*id)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostMessageIdUpdate) SetPost(v *Post) *PostMessageIdUpdate {
	return _u.SetPostID(v.ID)
}

// Mutation returns the PostMessageIdMutation object of the builder.
func (_u *PostMessageIdUpdate) Mutation() *PostMessageIdMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostMessageIdUpdate) ClearPost() *PostMessageIdUpdate {
	_u.mutation.ClearPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostMessageIdUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMessageIdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostMessageIdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMessageIdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PostMessageIdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(postmessageid.Table, postmessageid.Columns, sqlgraph.NewFieldSpec(postmessageid.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(postmessageid.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(postmessageid.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(postmessageid.FieldMessageID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(postmessageid.FieldMessageID, field.TypeInt32, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmessageid.PostTable,
			Columns: []string{postmessageid.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmessageid.PostTable,
			Columns: []string{postmessageid.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmessageid.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostMessageIdUpdateOne is the builder for updating a single PostMessageId entity.
type PostMessageIdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMessageIdMutation
}

// SetChatID sets the "chat_id" field.
func (_u *PostMessageIdUpdateOne) SetChatID(v int64) *PostMessageIdUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *PostMessageIdUpdateOne) SetNillableChatID(v *int64) *PostMessageIdUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *PostMessageIdUpdateOne) AddChatID(v int64) *PostMessageIdUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *PostMessageIdUpdateOne) SetMessageID(v int32) *PostMessageIdUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *PostMessageIdUpdateOne) SetNillableMessageID(v *int32) *PostMessageIdUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *PostMessageIdUpdateOne) AddMessageID(v int32) *PostMessageIdUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (_u *PostMessageIdUpdateOne) SetPostID(id uuidv7.UUID) *PostMessageIdUpdateOne {
	_u.mutation.SetPostID(id)
	return _u
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (_u *PostMessageIdUpdateOne) SetNillablePostID(id *uuidv7.UUID) *PostMessageIdUpdateOne {
	if id != nil {
		_u = _u.SetPostID(*id)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostMessageIdUpdateOne) SetPost(v *Post) *PostMessageIdUpdateOne {
	return _u.SetPostID(v.ID)
}

// Mutation returns the PostMessageIdMutation object of the builder.
func (_u *PostMessageIdUpdateOne) Mutation() *PostMessageIdMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostMessageIdUpdateOne) ClearPost() *PostMessageIdUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// Where appends a list predicates to the PostMessageIdUpdate builder.
func (_u *PostMessageIdUpdateOne) Where(ps ...predicate.PostMessageId) *PostMessageIdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostMessageIdUpdateOne) Select(field string, fields ...string) *PostMessageIdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostMessageId entity.
func (_u *PostMessageIdUpdateOne) Save(ctx context.Context) (*PostMessageId, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMessageIdUpdateOne) SaveX(ctx context.Context) *PostMessageId {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostMessageIdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMessageIdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PostMessageIdUpdateOne) sqlSave(ctx context.Context) (_node *PostMessageId, err error) {
	_spec := sqlgraph.NewUpdateSpec(postmessageid.Table, postmessageid.Columns, sqlgraph.NewFieldSpec(postmessageid.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostMessageId.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postmessageid.FieldID)
		for _, f := range fields {
			if !postmessageid.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postmessageid.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(postmessageid.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(postmessageid.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(postmessageid.FieldMessageID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(postmessageid.FieldMessageID, field.TypeInt32, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmessageid.PostTable,
			Columns: []string{postmessageid.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmessageid.PostTable,
			Columns: []string{postmessageid.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostMessageId{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmessageid.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
