// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/post"
	"channel-helper-go/ent/postmessageid"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuidv7 "github.com/moroz/uuidv7-go"
)

// PostMessageIdCreate is the builder for creating a PostMessageId entity.
type PostMessageIdCreate struct {
	config
	mutation *PostMessageIdMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (_c *PostMessageIdCreate) SetChatID(v int64) *PostMessageIdCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *PostMessageIdCreate) SetMessageID(v int32) *PostMessageIdCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (_c *PostMessageIdCreate) SetPostID(id uuidv7.UUID) *PostMessageIdCreate {
	_c.mutation.SetPostID(id)
	return _c
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (_c *PostMessageIdCreate) SetNillablePostID(id *uuidv7.UUID) *PostMessageIdCreate {
	if id != nil {
		_c = _c.SetPostID(*id)
	}
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PostMessageIdCreate) SetPost(v *Post) *PostMessageIdCreate {
	return _c.SetPostID(v.ID)
}

// Mutation returns the PostMessageIdMutation object of the builder.
func (_c *PostMessageIdCreate) Mutation() *PostMessageIdMutation {
	return _c.mutation
}

// Save creates the PostMessageId in the database.
func (_c *PostMessageIdCreate) Save(ctx context.Context) (*PostMessageId, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostMessageIdCreate) SaveX(ctx context.Context) *PostMessageId {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostMessageIdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostMessageIdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostMessageIdCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "PostMessageId.chat_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "PostMessageId.message_id"`)}
	}
	return nil
}

func (_c *PostMessageIdCreate) sqlSave(ctx context.Context) (*PostMessageId, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostMessageIdCreate) createSpec() (*PostMessageId, *sqlgraph.CreateSpec) {
	var (
		_node = &PostMessageId{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(postmessageid.Table, sqlgraph.NewFieldSpec(postmessageid.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(postmessageid.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(postmessageid.FieldMessageID, field.TypeInt32, value)
		_node.MessageID = value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmessageid.PostTable,
			Columns: []string{postmessageid.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.post_message_ids = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostMessageIdCreateBulk is the builder for creating many PostMessageId entities in bulk.
type PostMessageIdCreateBulk struct {
	config
	err      error
	builders []*PostMessageIdCreate
}

// Save creates the PostMessageId entities in the database.
func (_c *PostMessageIdCreateBulk) Save(ctx context.Context) ([]*PostMessageId, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostMessageId, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMessageIdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostMessageIdCreateBulk) SaveX(ctx context.Context) []*PostMessageId {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostMessageIdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostMessageIdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
