// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/postmessageid"
	"channel-helper-go/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostMessageIdDelete is the builder for deleting a PostMessageId entity.
type PostMessageIdDelete struct {
	config
	hooks    []Hook
	mutation *PostMessageIdMutation
}

// Where appends a list predicates to the PostMessageIdDelete builder.
func (_d *PostMessageIdDelete) Where(ps ...predicate.PostMessageId) *PostMessageIdDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PostMessageIdDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostMessageIdDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PostMessageIdDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postmessageid.Table, sqlgraph.NewFieldSpec(postmessageid.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PostMessageIdDeleteOne is the builder for deleting a single PostMessageId entity.
type PostMessageIdDeleteOne struct {
	_d *PostMessageIdDelete
}

// Where appends a list predicates to the PostMessageIdDelete builder.
func (_d *PostMessageIdDeleteOne) Where(ps ...predicate.PostMessageId) *PostMessageIdDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PostMessageIdDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postmessageid.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostMessageIdDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
