// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/post"
	"channel-helper-go/ent/schema"
	"channel-helper-go/ent/uploadtask"
	"time"

	uuidv7 "github.com/moroz/uuidv7-go"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescIsSent is the schema descriptor for is_sent field.
	postDescIsSent := postFields[3].Descriptor()
	// post.DefaultIsSent holds the default value on creation for the is_sent field.
	post.DefaultIsSent = postDescIsSent.Default.(bool)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[4].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescID is the schema descriptor for id field.
	postDescID := postFields[0].Descriptor()
	// post.DefaultID holds the default value on creation for the id field.
	post.DefaultID = postDescID.Default.(func() uuidv7.UUID)
	uploadtaskFields := schema.UploadTask{}.Fields()
	_ = uploadtaskFields
	// uploadtaskDescIsProcessed is the schema descriptor for is_processed field.
	uploadtaskDescIsProcessed := uploadtaskFields[3].Descriptor()
	// uploadtask.DefaultIsProcessed holds the default value on creation for the is_processed field.
	uploadtask.DefaultIsProcessed = uploadtaskDescIsProcessed.Default.(bool)
	// uploadtaskDescCreatedAt is the schema descriptor for created_at field.
	uploadtaskDescCreatedAt := uploadtaskFields[4].Descriptor()
	// uploadtask.DefaultCreatedAt holds the default value on creation for the created_at field.
	uploadtask.DefaultCreatedAt = uploadtaskDescCreatedAt.Default.(func() time.Time)
	// uploadtaskDescID is the schema descriptor for id field.
	uploadtaskDescID := uploadtaskFields[0].Descriptor()
	// uploadtask.DefaultID holds the default value on creation for the id field.
	uploadtask.DefaultID = uploadtaskDescID.Default.(func() uuidv7.UUID)
}
