// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/imagehash"
	"channel-helper-go/ent/predicate"
	"channel-helper-go/ent/uploadtask"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadTaskUpdate is the builder for updating UploadTask entities.
type UploadTaskUpdate struct {
	config
	hooks    []Hook
	mutation *UploadTaskMutation
}

// Where appends a list predicates to the UploadTaskUpdate builder.
func (_u *UploadTaskUpdate) Where(ps ...predicate.UploadTask) *UploadTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *UploadTaskUpdate) SetType(v uploadtask.Type) *UploadTaskUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableType(v *uploadtask.Type) *UploadTaskUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *UploadTaskUpdate) SetData(v []byte) *UploadTaskUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *UploadTaskUpdate) ClearData() *UploadTaskUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetIsProcessed sets the "is_processed" field.
func (_u *UploadTaskUpdate) SetIsProcessed(v bool) *UploadTaskUpdate {
	_u.mutation.SetIsProcessed(v)
	return _u
}

// SetNillableIsProcessed sets the "is_processed" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableIsProcessed(v *bool) *UploadTaskUpdate {
	if v != nil {
		_u.SetIsProcessed(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadTaskUpdate) SetCreatedAt(v time.Time) *UploadTaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableCreatedAt(v *time.Time) *UploadTaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *UploadTaskUpdate) SetSentAt(v time.Time) *UploadTaskUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableSentAt(v *time.Time) *UploadTaskUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *UploadTaskUpdate) ClearSentAt() *UploadTaskUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetImageHashID sets the "image_hash" edge to the ImageHash entity by ID.
func (_u *UploadTaskUpdate) SetImageHashID(id int) *UploadTaskUpdate {
	_u.mutation.SetImageHashID(id)
	return _u
}

// SetNillableImageHashID sets the "image_hash" edge to the ImageHash entity by ID if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableImageHashID(id *int) *UploadTaskUpdate {
	if id != nil {
		_u = _u.SetImageHashID(*id)
	}
	return _u
}

// SetImageHash sets the "image_hash" edge to the ImageHash entity.
func (_u *UploadTaskUpdate) SetImageHash(v *ImageHash) *UploadTaskUpdate {
	return _u.SetImageHashID(v.ID)
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_u *UploadTaskUpdate) Mutation() *UploadTaskMutation {
	return _u.mutation
}

// ClearImageHash clears the "image_hash" edge to the ImageHash entity.
func (_u *UploadTaskUpdate) ClearImageHash() *UploadTaskUpdate {
	_u.mutation.ClearImageHash()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadTaskUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := uploadtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UploadTask.type": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadtask.Table, uploadtask.Columns, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(uploadtask.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(uploadtask.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(uploadtask.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsProcessed(); ok {
		_spec.SetField(uploadtask.FieldIsProcessed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadtask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(uploadtask.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(uploadtask.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.ImageHashCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   uploadtask.ImageHashTable,
			Columns: []string{uploadtask.ImageHashColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagehash.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImageHashIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   uploadtask.ImageHashTable,
			Columns: []string{uploadtask.ImageHashColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagehash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadTaskUpdateOne is the builder for updating a single UploadTask entity.
type UploadTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadTaskMutation
}

// SetType sets the "type" field.
func (_u *UploadTaskUpdateOne) SetType(v uploadtask.Type) *UploadTaskUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableType(v *uploadtask.Type) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *UploadTaskUpdateOne) SetData(v []byte) *UploadTaskUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *UploadTaskUpdateOne) ClearData() *UploadTaskUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetIsProcessed sets the "is_processed" field.
func (_u *UploadTaskUpdateOne) SetIsProcessed(v bool) *UploadTaskUpdateOne {
	_u.mutation.SetIsProcessed(v)
	return _u
}

// SetNillableIsProcessed sets the "is_processed" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableIsProcessed(v *bool) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetIsProcessed(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadTaskUpdateOne) SetCreatedAt(v time.Time) *UploadTaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableCreatedAt(v *time.Time) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *UploadTaskUpdateOne) SetSentAt(v time.Time) *UploadTaskUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableSentAt(v *time.Time) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *UploadTaskUpdateOne) ClearSentAt() *UploadTaskUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetImageHashID sets the "image_hash" edge to the ImageHash entity by ID.
func (_u *UploadTaskUpdateOne) SetImageHashID(id int) *UploadTaskUpdateOne {
	_u.mutation.SetImageHashID(id)
	return _u
}

// SetNillableImageHashID sets the "image_hash" edge to the ImageHash entity by ID if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableImageHashID(id *int) *UploadTaskUpdateOne {
	if id != nil {
		_u = _u.SetImageHashID(*id)
	}
	return _u
}

// SetImageHash sets the "image_hash" edge to the ImageHash entity.
func (_u *UploadTaskUpdateOne) SetImageHash(v *ImageHash) *UploadTaskUpdateOne {
	return _u.SetImageHashID(v.ID)
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_u *UploadTaskUpdateOne) Mutation() *UploadTaskMutation {
	return _u.mutation
}

// ClearImageHash clears the "image_hash" edge to the ImageHash entity.
func (_u *UploadTaskUpdateOne) ClearImageHash() *UploadTaskUpdateOne {
	_u.mutation.ClearImageHash()
	return _u
}

// Where appends a list predicates to the UploadTaskUpdate builder.
func (_u *UploadTaskUpdateOne) Where(ps ...predicate.UploadTask) *UploadTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadTaskUpdateOne) Select(field string, fields ...string) *UploadTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UploadTask entity.
func (_u *UploadTaskUpdateOne) Save(ctx context.Context) (*UploadTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadTaskUpdateOne) SaveX(ctx context.Context) *UploadTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadTaskUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := uploadtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UploadTask.type": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadTaskUpdateOne) sqlSave(ctx context.Context) (_node *UploadTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadtask.Table, uploadtask.Columns, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UploadTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadtask.FieldID)
		for _, f := range fields {
			if !uploadtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uploadtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(uploadtask.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(uploadtask.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(uploadtask.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsProcessed(); ok {
		_spec.SetField(uploadtask.FieldIsProcessed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadtask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(uploadtask.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(uploadtask.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.ImageHashCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   uploadtask.ImageHashTable,
			Columns: []string{uploadtask.ImageHashColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagehash.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImageHashIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   uploadtask.ImageHashTable,
			Columns: []string{uploadtask.ImageHashColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagehash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UploadTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
