// Code generated by ent, DO NOT EDIT.

package ent

import (
	"channel-helper-go/ent/uploadtask"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuidv7 "github.com/moroz/uuidv7-go"
)

// UploadTaskCreate is the builder for creating a UploadTask entity.
type UploadTaskCreate struct {
	config
	mutation *UploadTaskMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *UploadTaskCreate) SetType(v uploadtask.Type) *UploadTaskCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetData sets the "data" field.
func (_c *UploadTaskCreate) SetData(v []byte) *UploadTaskCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetIsProcessed sets the "is_processed" field.
func (_c *UploadTaskCreate) SetIsProcessed(v bool) *UploadTaskCreate {
	_c.mutation.SetIsProcessed(v)
	return _c
}

// SetNillableIsProcessed sets the "is_processed" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableIsProcessed(v *bool) *UploadTaskCreate {
	if v != nil {
		_c.SetIsProcessed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UploadTaskCreate) SetCreatedAt(v time.Time) *UploadTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableCreatedAt(v *time.Time) *UploadTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *UploadTaskCreate) SetSentAt(v time.Time) *UploadTaskCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableSentAt(v *time.Time) *UploadTaskCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetImageHash sets the "image_hash" field.
func (_c *UploadTaskCreate) SetImageHash(v string) *UploadTaskCreate {
	_c.mutation.SetImageHash(v)
	return _c
}

// SetNillableImageHash sets the "image_hash" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableImageHash(v *string) *UploadTaskCreate {
	if v != nil {
		_c.SetImageHash(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UploadTaskCreate) SetID(v uuidv7.UUID) *UploadTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableID(v *uuidv7.UUID) *UploadTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_c *UploadTaskCreate) Mutation() *UploadTaskMutation {
	return _c.mutation
}

// Save creates the UploadTask in the database.
func (_c *UploadTaskCreate) Save(ctx context.Context) (*UploadTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadTaskCreate) SaveX(ctx context.Context) *UploadTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadTaskCreate) defaults() {
	if _, ok := _c.mutation.IsProcessed(); !ok {
		v := uploadtask.DefaultIsProcessed
		_c.mutation.SetIsProcessed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uploadtask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uploadtask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadTaskCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "UploadTask.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := uploadtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UploadTask.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsProcessed(); !ok {
		return &ValidationError{Name: "is_processed", err: errors.New(`ent: missing required field "UploadTask.is_processed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UploadTask.created_at"`)}
	}
	return nil
}

func (_c *UploadTaskCreate) sqlSave(ctx context.Context) (*UploadTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuidv7.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadTaskCreate) createSpec() (*UploadTask, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadtask.Table, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(uploadtask.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(uploadtask.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.IsProcessed(); ok {
		_spec.SetField(uploadtask.FieldIsProcessed, field.TypeBool, value)
		_node.IsProcessed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uploadtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(uploadtask.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if value, ok := _c.mutation.ImageHash(); ok {
		_spec.SetField(uploadtask.FieldImageHash, field.TypeString, value)
		_node.ImageHash = value
	}
	return _node, _spec
}

// UploadTaskCreateBulk is the builder for creating many UploadTask entities in bulk.
type UploadTaskCreateBulk struct {
	config
	err      error
	builders []*UploadTaskCreate
}

// Save creates the UploadTask entities in the database.
func (_c *UploadTaskCreateBulk) Save(ctx context.Context) ([]*UploadTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadTaskCreateBulk) SaveX(ctx context.Context) []*UploadTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
