// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ImageHash is the predicate function for imagehash builders.
type ImageHash func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostMessageId is the predicate function for postmessageid builders.
type PostMessageId func(*sql.Selector)

// UploadTask is the predicate function for uploadtask builders.
type UploadTask func(*sql.Selector)
